### ISSUE TITLE
accept height as an argument

### ISSUE THREAD

**Issue by ansis** [mapbox/bboxify-labels#3]
`bboxifyLabel` should accept height as an argument

**Comment by kapadia** [comment]
@ansis height for the box? or do you have something else in mind?

**Comment by ansis** [comment]
Yes, the height for the box which would be based on the text size.

**Comment by kapadia** [comment]
Done - on the packing branch https://github.com/mapbox/bboxify-labels/commit/3a257b2020d38e74f13b65cbfa54ed9b5c986663
