### ISSUE TITLE
vertical line bug

### ISSUE THREAD

**Issue by ansis** [mapbox/bboxify-labels#6]
I think there is a bug affecting vertical lines.

![screen shot 2015-02-20 at 4 01 26 pm](https://cloud.githubusercontent.com/assets/1421652/6311592/c5a908fc-b919-11e4-8b96-b32e9db328d5.png)

http://localhost:3000/debug/#16.6/38.93205/-77.04242

**Comment by kapadia** [comment]
@ansis this is fixed now by using the segment distance to talk along the segment when the line is vertical.

**Comment by kapadia** [comment]
![vert](https://cloud.githubusercontent.com/assets/581337/6338100/2dfa9bde-bb61-11e4-9a29-0ccc29ad64e7.jpg)
*broken (left) fixed (right)
